### ISSUE TITLE
Not able to use it ,Failed to resolve: com.github.DmytroShuba:DailyTags:1.0.0

### ISSUE THREAD

**Issue by vishalx4** [DmytroShuba/DailyTags#1]
i have added  `implementation "com.github.DmytroShuba:DailyTags:1.0.0"` in app level build.gradle 
and 
`buildscript {
    repositories {
        maven { url 'https://jitpack.io' }
    }
    ext {
        compose_version = '1.0.1'
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
`
this in project level build.gradle file

**Comment by DmytroShuba** [comment]
Hi, thank you for your request!

Looks like you added the dependencies and repository correctly. However, your repositories list should also have the default repositories such as `google()` and `mavenCentral()`. It should look like this:
```koltin
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
```
