### ISSUE TITLE
Error parsing two <a href> tags in the same string

### ISSUE THREAD

**Issue by PabloMGrela** [DmytroShuba/DailyTags#2]
When there are more than one <a href> tag in the string, the first closing </a> is ignoring, so all text from first <a href> until last </a> is highlighted, or even the first text is not rendered at all.

Example test to reproduce it:` <![CDATA[ I <b>accept</b> the <a href=\"www.bing.com">Terms and Conditions</a> and have read the <a href=\"www.google.es\">Privacy Notice</a>]]>`

**Comment by DmytroShuba** [comment]
Hi, thank you for the question!

First, make sure you created a correct pattern and rule for the `CDATA` tag. Here is a wiki page about [custom rules](https://github.com/DmytroShuba/DailyTags/wiki/Add-custom-tags-and-markups).

Second, `<![CDATA[ I <b>accept</b> the <a href=\"www.bing.com">Terms and Conditions</a> and have read the <a href=\"www.google.es\">Privacy Notice</a>]]>` is a an example of a string with nested tags. The bold text "accept" and the link after it are inside `CDATA`. Nested tags feature is not supported yet ([list of supported features](https://github.com/DmytroShuba/DailyTags/wiki/Supported-features)). It will be added in future releases.
For now, [here](https://github.com/DmytroShuba/DailyTags/issues/3#issuecomment-1129899542) is a small workaround to handle nested tags until it is fully supported in newer versions of the library.
