### ISSUE TITLE
Html - Bold text in ListItem

### ISSUE THREAD

**Issue by fairEnough83** [DmytroShuba/DailyTags#3]
Great library, thank you for this. Just found one issue. I cannot add a bold text segment inside an unordered list. 

`<li>Tap to open the <b>phone settings</b> and search for <b>Device Care</b></li>`

this is rendering a list item but the text contain the bold tags. Is this on purpose? How can I achieve that the bold segments are rendered bold as well?

**Comment by DmytroShuba** [comment]
Thank you! I'm glad you like the library.
DailyTags does not support nested tags yet. You can find the full list of supported features [here](https://github.com/DmytroShuba/DailyTags/wiki/Supported-features).

However, nested tags support will be added in future releases.

For now, the easiest way to get around this restriction would be to additionally parse the content to reach the nested tags.

```kotlin
    // render list first and retrieve the final string
    val renderedList = parser.parse(source, rules).render().toAnnotatedString().text
    // now render what is inside list (second level tags)
    val renderedBold = parser.parse(renderedList, rules).render().toAnnotatedString()

    Text(text = renderedBold)
```

Let me know if it works for you :)
